### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Lytjoe** [0xD34D/barinsta#1]
- [X] My app is *at least* at the current release version. I understand that any versions before that is not supported.
- [Website is not available] I have read [the FAQ] (https://barinsta.austinhuang.me/en/latest/faq.html).

The app completely crashes, when I try to view my saved posts.

## Steps

1. Open the app.
2. Go to your profile.
3. Click on 'Saved'.
4. The app crashes.

## Environment

 - Device: Samsung Galaxy S8
 - Android version: 9#

**Comment by arshcheema4570** [comment]
I also in counter crashes when I send posts to some one and also there are unexpected crashes which are not bound to any specific activity 
New Trace collected:
=====================
IMPORTANT: If sending by email, your email address and the entire content will be made public at https://github.com/austinhuang0131/barinsta/issues.

When possible, please describe the steps leading to this crash. Thank you for your cooperation.

Error report collected on: 2022-05-21T06:35:16.534

Information:
==============
VERSION      : 19.2.4-fdroid
VERSION_CODE : 65
PHONE-MODEL     : Redmi Note 7 Pro
ANDROID_VERS : 10
ANDROID_REL     : 29
BRAND   : xiaomi
MANUFACTURER : Xiaomi
BOARD   : violet
DEVICE   : violet
PRODUCT      : violet
HOST   : c4-miui-ota-bd186.bj
TAGS   : release-keys

Stack:
==============
java.lang.NullPointerException: null cannot be cast to non-null type awais.instagrabber.repositories.responses.directmessages.RankedRecipient
 at java.util.Objects.requireNonNull(Objects.java:228)
 at awais.instagrabber.fragments.-$$Lambda$UserSearchFragment$n-S0R3bFLpW66qt4sOaImFfVEIA.onClick(lambda:23)
 at awais.instagrabber.adapters.viewholder.directmessages.-$$Lambda$RecipientThreadViewHolder$i9UX7yPnw0YPDC6DwJx3DlnVVr8.onClick(lambda:2)
 at android.view.View.performClick(View.java:7189)
 at android.view.View.performClickInternal(View.java:7166)
 at android.view.View.access$3500(View.java:819)
 at android.view.View$PerformClick.run(View.java:27682)
 at android.os.Handler.handleCallback(Handler.java:883)
 at android.os.Handler.dispatchMessage(Handler.java:100)
 at android.os.Looper.loop(Looper.java:224)
 at android.app.ActivityThread.main(ActivityThread.java:7592)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)


*** End of current Report ***
